#!/usr/bin/env python3
"""Convert the vendored VGLC Lode Runner level corpus into levels.js.

Source data: levels/vglc-source/Level 1.txt .. Level 150.txt, vendored
verbatim from TheVGLC (MIT license): https://github.com/TheVGLC/TheVGLC
"Lode Runner/Processed" — a plain-text transcription of the 150 levels
from the original 1983 Broderbund release (design: Douglas E. Smith).

VGLC tile legend (see levels/vglc-source, or Loderunner.json in the
source repo):
    B  solid, undiggable ground
    b  solid, diggable ground
    .  passable, empty
    -  passable, climbable rope / hand-over-hand bar
    #  passable, climbable ladder
    G  passable, pickupable gold
    E  enemy spawn (VGLC doesn't distinguish runner vs. grunter)
    M  player spawn

Re-run this script whenever levels/vglc-source changes:
    python3 scripts/build_levels.py
"""
import os
import re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
SOURCE_DIR = os.path.join(REPO_ROOT, "levels", "vglc-source")
OUTPUT_PATH = os.path.join(REPO_ROOT, "levels.js")
LEVEL_COUNT = 150

# VGLC char -> our engine's LEVEL_ASCII char (see game.js parseLevel()).
# 'M' (player spawn) and 'E' (enemy spawn) are handled specially below
# rather than through this table, since they need extra bookkeeping.
TILE_MAP = {
    ".": ".",  # empty
    "B": "|",  # solid / undiggable
    "b": "#",  # brick / diggable
    "#": "L",  # ladder
    "-": "~",  # rope / hand-over-hand bar (NEW — engine doesn't act on
               # this yet; parseLevel() will treat unknown chars as
               # empty until rope movement is implemented)
    "G": "g",  # gold
}

# All VGLC enemy spawns default to the runner type for now — the source
# corpus doesn't distinguish runner vs. grunter, so this is a deliberate
# placeholder pending a gameplay-balance pass, not a data-fidelity call.
ENEMY_SPAWN_CHAR = "r"


def convert_level(level_id, raw_text):
    rows = raw_text.splitlines()
    tile_rows = []
    player_spawn = None
    gold_total = 0
    enemy_count = 0

    for row_idx, row in enumerate(rows):
        out_row = []
        for col_idx, ch in enumerate(row):
            if ch == "M":
                if player_spawn is not None:
                    raise ValueError(
                        f"Level {level_id}: multiple 'M' spawns "
                        f"(row {row_idx}, col {col_idx})"
                    )
                player_spawn = {"col": col_idx, "row": row_idx}
                out_row.append(".")
            elif ch == "E":
                enemy_count += 1
                out_row.append(ENEMY_SPAWN_CHAR)
            elif ch == "G":
                gold_total += 1
                out_row.append(TILE_MAP["G"])
            elif ch in TILE_MAP:
                out_row.append(TILE_MAP[ch])
            else:
                raise ValueError(
                    f"Level {level_id}: unrecognized tile {ch!r} "
                    f"(row {row_idx}, col {col_idx})"
                )
        tile_rows.append("".join(out_row))

    return {
        "id": level_id,
        "tiles": tile_rows,
        "playerSpawn": player_spawn,
        "goldTotal": gold_total,
        "enemyCount": enemy_count,
    }


def js_string_literal(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_level(level):
    spawn = level["playerSpawn"]
    spawn_js = (
        f'{{ col: {spawn["col"]}, row: {spawn["row"]} }}'
        if spawn is not None
        else "null /* no spawn in source data — see NOTES.md */"
    )
    tiles_js = ",\n      ".join(js_string_literal(r) for r in level["tiles"])
    return (
        "  {\n"
        f'    id: {level["id"]},\n'
        f"    playerSpawn: {spawn_js},\n"
        f'    goldTotal: {level["goldTotal"]},\n'
        f'    enemyCount: {level["enemyCount"]},\n'
        "    tiles: [\n"
        f"      {tiles_js}\n"
        "    ],\n"
        "  }"
    )


def main():
    levels = []
    for i in range(1, LEVEL_COUNT + 1):
        path = os.path.join(SOURCE_DIR, f"Level {i}.txt")
        with open(path, "r", encoding="utf-8") as f:
            raw = f.read()
        levels.append(convert_level(i, raw))

    no_spawn = [lv["id"] for lv in levels if lv["playerSpawn"] is None]

    header = f"""/* Auto-generated by scripts/build_levels.py — do not hand-edit.
 *
 * {LEVEL_COUNT} levels converted from the vendored VGLC corpus
 * (levels/vglc-source/, MIT license, https://github.com/TheVGLC/TheVGLC),
 * itself a transcription of the original 1983 Broderbund Lode Runner
 * levels (design: Douglas E. Smith).
 *
 * Tile chars match game.js's LEVEL_ASCII scheme, plus one addition:
 * '~' = rope / hand-over-hand bar (not yet acted on by the engine —
 * parseLevel() currently treats unrecognized chars as empty, so these
 * tiles are inert until rope movement is implemented).
 *
 * Levels with playerSpawn: null had no 'M' marker in the source data
 * (currently just level 150 — the source's finale "vault" screen).
 * Re-run: python3 scripts/build_levels.py
 */
(() => {{
  'use strict';

  const LEVELS = [
{",\n".join(render_level(lv) for lv in levels)}
  ];

  window.LEVELS = LEVELS;
}})();
"""

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"Wrote {len(levels)} levels to {OUTPUT_PATH}")
    if no_spawn:
        print(f"Levels with no player spawn in source data: {no_spawn}")


if __name__ == "__main__":
    main()
