#!/usr/bin/env python3
"""Generate sprites.js: the runner and guard, as 14x11 pixel frames.

These are original drawings, not copies of the 1983 art. The originals
were studied for what matters visually — thin 2-3px limbs, a blue pixel
on top of the head, a white runner against an orange guard with white
legs, and which frames exist (run x3, hand-over-hand x3, climb x2, dig,
fall) — and every pose here is our own joint data drawn as lines. That
keeps the look faithful without redistributing Brøderbund's artwork.

Frames face right; the game mirrors them for left. Palette codes:
  w white   o orange   b blue   . empty
Re-run after editing a pose:  python3 scripts/build_sprites.py
"""
import json
import os

W, H = 14, 11
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Each pose: dy shifts head+torso down (hanging), lean shifts the upper
# body forward, arms/legs are joint polylines (shoulder/hip -> ... -> hand/foot).
POSES = {
    "run0": dict(lean=1, arms=[[(7, 4), (5, 5), (4, 6)], [(8, 4), (10, 5), (11, 4)]],
                 legs=[[(7, 7), (9, 8), (10, 10)], [(6, 7), (5, 9), (3, 10)]]),
    "run1": dict(lean=0, arms=[[(6, 4), (5, 5), (6, 6)], [(7, 4), (9, 5), (9, 6)]],
                 legs=[[(6, 7), (6, 9), (6, 10)], [(7, 7), (8, 8), (9, 9)]]),
    "run2": dict(lean=1, arms=[[(7, 4), (9, 5), (10, 6)], [(8, 4), (6, 5), (5, 4)]],
                 legs=[[(7, 7), (8, 9), (8, 10)], [(6, 7), (4, 8), (3, 10)]]),
    "monkey0": dict(dy=1, arms=[[(6, 3), (5, 1), (5, 0)], [(8, 3), (9, 2), (9, 0)]],
                    legs=[[(6, 8), (6, 10)], [(7, 8), (8, 9), (8, 10)]]),
    "monkey1": dict(dy=1, arms=[[(6, 3), (6, 1), (6, 0)], [(8, 3), (9, 1), (9, 0)]],
                    legs=[[(6, 8), (6, 10)], [(7, 8), (7, 10)]]),
    "monkey2": dict(dy=1, arms=[[(6, 3), (5, 2), (5, 0)], [(8, 3), (9, 1), (9, 0)]],
                    legs=[[(6, 8), (5, 9), (5, 10)], [(7, 8), (7, 10)]]),
    "climb0": dict(arms=[[(6, 3), (5, 1), (5, 0)], [(8, 4), (9, 5), (9, 6)]],
                   legs=[[(6, 7), (5, 8), (6, 9)], [(7, 7), (8, 9), (8, 10)]]),
    "climb1": dict(arms=[[(8, 3), (9, 1), (9, 0)], [(6, 4), (5, 5), (5, 6)]],
                   legs=[[(7, 7), (8, 8), (7, 9)], [(6, 7), (5, 9), (5, 10)]]),
    "dig": dict(arms=[[(6, 4), (5, 5), (5, 6)], [(8, 4), (10, 5), (12, 6)]],
                legs=[[(6, 7), (5, 9), (5, 10)], [(7, 7), (8, 9), (8, 10)]], gun=True),
    "fall": dict(arms=[[(6, 3), (4, 2), (3, 0)], [(8, 3), (10, 2), (11, 0)]],
                 legs=[[(6, 7), (5, 9), (5, 10)], [(7, 7), (8, 9), (8, 10)]]),
}


def line(g, a, b, c):
    (x0, y0), (x1, y1) = a, b
    dx, dy = abs(x1 - x0), -abs(y1 - y0)
    sx, sy = (1 if x0 < x1 else -1), (1 if y0 < y1 else -1)
    err = dx + dy
    while True:
        put(g, x0, y0, c)
        if (x0, y0) == (x1, y1):
            break
        e2 = 2 * err
        if e2 >= dy:
            err += dy
            x0 += sx
        if e2 <= dx:
            err += dx
            y0 += sy


def put(g, x, y, c):
    if 0 <= x < W and 0 <= y < H:
        g[y][x] = c


def figure(pose, kind):
    """kind 'runner': white all over. 'guard': orange head/torso/arms, white legs."""
    body = "w" if kind == "runner" else "o"
    legc = "w"
    g = [["."] * W for _ in range(H)]
    lean, dy = pose.get("lean", 0), pose.get("dy", 0)
    for a in pose["legs"]:
        for i in range(len(a) - 1):
            line(g, a[i], a[i + 1], legc)
    # torso: 2 wide (guard: 3 wide through the shoulders); leans at the top
    for row in range(3, 7):
        x = 6 + (lean if row <= 4 else 0)
        for cx in ([x, x + 1] if kind == "runner" else [x - (1 if row <= 5 else 0), x, x + 1]):
            put(g, cx, row + dy, body)
    if kind == "runner":
        put(g, 6, 6 + dy, "o")                        # belt
    for a in pose["arms"]:
        for i in range(len(a) - 1):
            line(g, a[i], a[i + 1], body)
    hx = 6 + lean
    for (cx, cy) in [(hx, 1), (hx + 1, 1), (hx, 2), (hx + 1, 2)]:
        put(g, cx, cy + dy, body)
    put(g, hx + 1, 0 + dy, "b")                       # the blue pixel on top
    if kind == "guard":
        put(g, hx + 1, 2 + dy, "w")                   # a white eye toward the front
    if pose.get("gun"):
        put(g, 12, 6, "o"); put(g, 11, 6, "o"); put(g, 12, 7, "o")
    return ["".join(r) for r in g]


def build():
    out = {"player": {}, "guard": {}}
    groups = {
        "run": ["run0", "run1", "run2"],
        "monkey": ["monkey0", "monkey1", "monkey2"],
        "climb": ["climb0", "climb1"],
        "fall": ["fall"],
    }
    for name, poses in groups.items():
        out["player"][name] = [figure(POSES[p], "runner") for p in poses]
        out["guard"][name] = [figure(POSES[p], "guard") for p in poses]
    out["player"]["dig"] = [figure(POSES["dig"], "runner")]
    return out


if __name__ == "__main__":
    data = build()
    js = (
        "/* Auto-generated by scripts/build_sprites.py — do not hand-edit.\n"
        " * Original 14x11 pixel drawings of the runner and guard, in the style\n"
        " * of the 1983 Apple II art (not copies of it). Frames face right; the\n"
        " * game mirrors them for left. w white, o orange, b blue, . empty. */\n"
        "window.SPRITES = " + json.dumps(data, indent=1) + ";\n"
    )
    with open(os.path.join(ROOT, "sprites.js"), "w") as f:
        f.write(js)
    n = sum(len(v) for d in data.values() for v in d.values())
    print(f"Wrote sprites.js ({n} frames)")
