#!/usr/bin/env python3
"""Generate levels.js: the 150 levels of the 1983 Apple II Lode Runner.

Source: lodeRunner.v.classic.js from SimonHung/LodeRunner_TotalRecall, whose
header says the levels were extracted from the Apple II disk image. They are
28x16, one player start each, and — unlike the levels this project used
before — they keep the two tile types the earlier data dropped:

    S  hidden ladder: invisible until every piece of gold is collected, then
       it appears and gives the way out (111 of the 150 levels have one)
    X  trapdoor: looks like brick but you fall through it (85 levels)

Rights note: the level designs are Doug Smith's / Brøderbund's, and that
repository states no licence, so this project has no licence to them either.

Tile mapping (source char -> our char):
    ' ' -> .   empty            '#' -> #   brick (diggable)
    '@' -> |   solid            'H' -> L   ladder
    '-' -> ~   rope             '$' -> g   gold
    '0' -> r   guard spawn      'X' -> X   trapdoor
    'S' -> S   hidden ladder    '&' -> (player spawn, stored separately, tile empty)

    python3 scripts/build_levels.py                 # download + build
    python3 scripts/build_levels.py --src FILE      # use a local copy
"""
import argparse
import json
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URL = "https://raw.githubusercontent.com/SimonHung/LodeRunner_TotalRecall/HEAD/lodeRunner.v.classic.js"
COLS, ROWS, COUNT = 28, 16, 150
MAP = {" ": ".", "#": "#", "@": "|", "H": "L", "-": "~", "$": "g", "0": "r", "X": "X", "S": "S"}


def convert(idx, rows):
    tiles, spawn, gold, enemies = [], None, 0, 0
    for r, line in enumerate(rows):
        out = []
        for c, ch in enumerate(line):
            if ch == "&":
                if spawn is not None:
                    raise ValueError(f"level {idx}: two player starts")
                spawn = {"col": c, "row": r}
                out.append(".")
            elif ch in MAP:
                out.append(MAP[ch])
                gold += ch == "$"
                enemies += ch == "0"
            else:
                raise ValueError(f"level {idx}: unknown tile {ch!r} at ({c},{r})")
        tiles.append("".join(out))
    if spawn is None:
        raise ValueError(f"level {idx}: no player start")
    return {"id": idx, "playerSpawn": spawn, "goldTotal": gold, "enemyCount": enemies, "tiles": tiles}


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", help="local lodeRunner.v.classic.js (default: download)")
    args = ap.parse_args()
    text = open(args.src).read() if args.src else urllib.request.urlopen(URL).read().decode()
    rows = re.findall(r'"([^"\n]{%d})"' % COLS, text)
    if len(rows) != COUNT * ROWS:
        raise SystemExit(f"expected {COUNT * ROWS} rows, found {len(rows)}")
    levels = [convert(i + 1, rows[i * ROWS:(i + 1) * ROWS]) for i in range(COUNT)]

    js = (
        "/* Auto-generated by scripts/build_levels.py — do not hand-edit.\n"
        " * The 150 levels of the 1983 Apple II Lode Runner, extracted from the\n"
        " * disk image by Simon Hung (SimonHung/LodeRunner_TotalRecall). 28x16.\n"
        " * '.' empty  '#' brick  '|' solid  'L' ladder  '~' rope  'g' gold\n"
        " * 'r' guard  'X' trapdoor  'S' hidden ladder (appears once all gold\n"
        " * is collected). The player start is stored as playerSpawn. */\n"
        "window.LEVELS = " + json.dumps(levels, separators=(",", ":")) + ";\n"
    )
    with open(os.path.join(ROOT, "levels.js"), "w") as f:
        f.write(js)
    hid = sum(any("S" in t for t in lv["tiles"]) for lv in levels)
    trap = sum(any("X" in t for t in lv["tiles"]) for lv in levels)
    print(f"Wrote levels.js: {len(levels)} levels, {hid} with hidden ladders, {trap} with trapdoors")
